services:
  file:
    image: ${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: always
    env_file:
      - ./.env
      - ./../.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${FILES_DIR}:/files
    ports:
      - "${FILE_PORT}:${FILE_PORT}"
    stdin_open: true
    tty: true
